name: mlflow-examples-keras_tf_mnist
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow==1.12.0
    - tensorflow==2.3.0
    - onnx==1.7.0
    - onnxmltools==1.7.0
    - onnxruntime==1.4.0
    - Pillow==2.2.2
