name: mlflow-examples-sparkml
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip=19.0.3
  - pip:
    - mlflow==1.12.0
    - mleap==0.15.0
    - pyspark==2.4.5
    - pyarrow==0.17.1
    - onnx==1.7.0
    - onnxruntime==1.2.0
    - onnxmltools==1.6.1
